namespace FromModel;

internal record DefaultSource(string Name, string Code, string Filename)
{
    
    public static readonly DefaultSource FromModelAttribute = new(
        Name: "FromModel.FromModelAttribute",
        Code: """
            // <auto-generated/>
            #nullable enable
            namespace FromModel
            {
                [System.AttributeUsage(System.AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
                public sealed class FromModelAttribute : System.Attribute
                {
                    public System.Type ModelType { get; }
                    public string[] Ignore { get; set; } = System.Array.Empty<string>();
                    public bool IncludeInherited { get; set; }
                    public string[] Flatten { get; set; } = System.Array.Empty<string>();
                    public FlattenPrefix FlattenPrefix { get; set; }

                    public FromModelAttribute(System.Type modelType)
                    {
                        ModelType = modelType;
                    }
                }
            }        
        """,
        Filename: "FromModelAttribute.g.cs"
    );

    public static readonly DefaultSource TypeMappingAttribute = new(
        Name: "FromModel.TypeMappingAttribute",
        Code: """
            // <auto-generated/>
            namespace FromModel
            {
                [System.AttributeUsage(System.AttributeTargets.Class, Inherited = false, AllowMultiple = true)]
                public sealed class TypeMappingAttribute : System.Attribute
                {
                    public System.Type SourceType { get; }
                    public System.Type TargetType { get; }

                    public TypeMappingAttribute(System.Type sourceType, System.Type targetType)
                    {
                        SourceType = sourceType;
                        TargetType = targetType;
                    }
                }
            }
        """,
        Filename: "TypeMappingAttribute.g.cs"
    );

    public static readonly DefaultSource RenamePropertyAttribute = new(
        Name: "FromModel.RenamePropertyAttribute",
        Code: """
            // <auto-generated/>
            namespace FromModel
            {
                [System.AttributeUsage(System.AttributeTargets.Class, Inherited = false, AllowMultiple = true)]
                public sealed class RenamePropertyAttribute : System.Attribute
                {
                    public string SourceName { get; }
                    public string TargetName { get; }

                    public RenamePropertyAttribute(string sourceName, string targetName)
                    {
                        SourceName = sourceName;
                        TargetName = targetName;
                    }
                }
            }
        """,
        Filename: "RenamePropertyAttribute.g.cs"
    );

    public static readonly DefaultSource FlattenPrefixEnum = new(
        Name: "FromModel.FlattenPrefix",
        Code: """
            // <auto-generated/>
            namespace FromModel
            {
                public enum FlattenPrefix
                {
                    Parent = 0,
                    None = 1,
                    Gaped = 2
                }
            }
        """,
        Filename: "FlattenPrefix.g.cs"
    );

    public static DefaultSource[] All { get; } =
    [
        FromModelAttribute,
        TypeMappingAttribute,
        RenamePropertyAttribute,
        FlattenPrefixEnum,
    ];
}
