using System.Collections.Generic;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace FromModel;

[Generator]
public sealed partial class FromModelGenerator : IIncrementalGenerator
{
    private const string FromModelAttributeFullName = "FromModel.FromModelAttribute";
    private const string TypeMappingAttributeFullName = "FromModel.TypeMappingAttribute";

    private const string AttributeSource =
        @"// <auto-generated/>
#nullable enable
namespace FromModel
{
    [System.AttributeUsage(System.AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
    public sealed class FromModelAttribute : System.Attribute
    {
        public System.Type ModelType { get; }
        public string[] Ignore { get; set; } = System.Array.Empty<string>();
        public bool IncludeInherited { get; set; }
        public string[] Flatten { get; set; } = System.Array.Empty<string>();

        public FromModelAttribute(System.Type modelType)
        {
            ModelType = modelType;
        }
    }
}";

    private const string TypeMappingAttributeSource =
        @"// <auto-generated/>
namespace FromModel
{
    [System.AttributeUsage(System.AttributeTargets.Class, Inherited = false, AllowMultiple = true)]
    public sealed class TypeMappingAttribute : System.Attribute
    {
        public System.Type SourceType { get; }
        public System.Type TargetType { get; }

        public TypeMappingAttribute(System.Type sourceType, System.Type targetType)
        {
            SourceType = sourceType;
            TargetType = targetType;
        }
    }
}";

    private const string RenamePropertyAttributeFullName = "FromModel.RenamePropertyAttribute";

    private const string RenamePropertyAttributeSource =
        @"// <auto-generated/>
namespace FromModel
{
    [System.AttributeUsage(System.AttributeTargets.Class, Inherited = false, AllowMultiple = true)]
    public sealed class RenamePropertyAttribute : System.Attribute
    {
        public string SourceName { get; }
        public string TargetName { get; }

        public RenamePropertyAttribute(string sourceName, string targetName)
        {
            SourceName = sourceName;
            TargetName = targetName;
        }
    }
}";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx =>
        {
            ctx.AddSource("FromModelAttribute.g.cs", SourceText.From(AttributeSource, Encoding.UTF8));
            ctx.AddSource("TypeMappingAttribute.g.cs", SourceText.From(TypeMappingAttributeSource, Encoding.UTF8));
            ctx.AddSource("RenamePropertyAttribute.g.cs", SourceText.From(RenamePropertyAttributeSource, Encoding.UTF8));
        });

        var pipeline = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => IsPartialClassWithAttributes(node),
                transform: static (ctx, _) => ExtractClassTarget(ctx))
            .Where(static target => target is not null);

        context.RegisterSourceOutput(pipeline, static (ctx, target) => Emit(ctx, target!));
    }

    private static bool IsPartialClassWithAttributes(SyntaxNode node)
    {
        if (node is not ClassDeclarationSyntax cls) return false;
        if (cls.AttributeLists.Count == 0) return false;
        return cls.Modifiers.Any(SyntaxKind.PartialKeyword);
    }

    private static ClassTarget? ExtractClassTarget(GeneratorSyntaxContext context)
    {
        if (context.SemanticModel.GetDeclaredSymbol(context.Node) is not INamedTypeSymbol classSymbol)
            return null;

        if (!TryGetFromModelAttributeData(classSymbol, out AttributeData? attr)) return null;
        if (!TryGetModelSymbol(attr!, out INamedTypeSymbol? modelSymbol)) return null;

        var ns = classSymbol.ContainingNamespace is { IsGlobalNamespace: false } nsSymbol
            ? nsSymbol.ToDisplayString()
            : null;

        var accessibility = classSymbol.DeclaredAccessibility switch
        {
            Accessibility.Public => "public",
            Accessibility.Internal => "internal",
            Accessibility.Private => "private",
            Accessibility.Protected => "protected",
            Accessibility.ProtectedAndInternal => "private protected",
            Accessibility.ProtectedOrInternal => "protected internal",
            _ => "internal"
        };

        var ignoredNames     = GetIgnoredProperties(attr!);
        var flattenNames     = GetFlattenProperties(attr!);
        var includeInherited = GetIncludeInherited(attr!);
        var typeMappings     = GetTypeMappings(classSymbol);
        var renameMap        = GetRenameMap(classSymbol);

        var properties = new List<PropertyData>();
        foreach (var prop in GetModelProperties(modelSymbol!, includeInherited))
        {
            if (ignoredNames.Contains(prop.Name)) continue;

            if (flattenNames.Contains(prop.Name))
            {
                if (prop.Type is INamedTypeSymbol nestedType)
                    foreach (var nested in GetModelProperties(nestedType, includeInherited: false))
                        properties.Add(BuildPropertyData(nested, typeMappings, renameMap: null));
                continue;
            }

            properties.Add(BuildPropertyData(prop, typeMappings, renameMap));
        }

        return new ClassTarget(classSymbol.Name, ns, accessibility, properties);
    }

    private static string? GetInitializer(IPropertySymbol prop)
    {
        if (prop.DeclaringSyntaxReferences.Length > 0
            && prop.DeclaringSyntaxReferences[0].GetSyntax() is PropertyDeclarationSyntax propSyntax
            && propSyntax.Initializer is not null)
            return propSyntax.Initializer.Value.ToString();

        return null;
    }

    private static Dictionary<string, string> GetTypeMappings(INamedTypeSymbol classSymbol)
    {
        var typeMappings = new Dictionary<string, string>();
        foreach (var a in classSymbol.GetAttributes())
        {
            if (a.AttributeClass?.ToDisplayString() != TypeMappingAttributeFullName) continue;
            if (a.ConstructorArguments.Length < 2) continue;
            if (a.ConstructorArguments[0].Kind != TypedConstantKind.Type) continue;
            if (a.ConstructorArguments[1].Kind != TypedConstantKind.Type) continue;
            if (a.ConstructorArguments[0].Value is not INamedTypeSymbol sourceType) continue;
            if (a.ConstructorArguments[1].Value is not INamedTypeSymbol targetType) continue;
            typeMappings[sourceType.ToDisplayString()] = targetType.ToDisplayString();
        }

        return typeMappings;
    }

    private static HashSet<string> GetIgnoredProperties(AttributeData attr)
    {
        var ignoredNames = new HashSet<string>();
        foreach (var namedArg in attr.NamedArguments)
        {
            if (namedArg.Key != "Ignore") continue;

            foreach (var item in namedArg.Value.Values)
                if (item.Value is string name)
                    ignoredNames.Add(name);
        }

        return ignoredNames;
    }

    private static PropertyData BuildPropertyData(
        IPropertySymbol prop,
        Dictionary<string, string> typeMappings,
        Dictionary<string, string>? renameMap)
    {
        var typeDisplay = prop.Type.ToDisplayString();
        if (typeMappings.TryGetValue(typeDisplay, out var mapped))
            typeDisplay = mapped;

        var name = renameMap is not null && renameMap.TryGetValue(prop.Name, out var renamed)
            ? renamed
            : prop.Name;

        return new PropertyData(
            typeDisplay, name,
            prop.GetMethod is not null,
            prop.SetMethod is not null && !prop.SetMethod.IsInitOnly,
            prop.SetMethod is { IsInitOnly: true },
            prop.IsRequired,
            GetInitializer(prop));
    }

    private static IEnumerable<IPropertySymbol> GetModelProperties(
        INamedTypeSymbol modelSymbol, bool includeInherited)
    {
        var seenNames = new HashSet<string>();
        var current = modelSymbol;

        while (current is not null && current.SpecialType != SpecialType.System_Object)
        {
            foreach (var member in current.GetMembers())
            {
                if (member is not IPropertySymbol prop) continue;
                if (prop.DeclaredAccessibility != Accessibility.Public) continue;
                if (prop.IsStatic) continue;
                if (!seenNames.Add(prop.Name)) continue;
                yield return prop;
            }
            if (!includeInherited) break;
            current = current.BaseType;
        }
    }

    private static bool GetIncludeInherited(AttributeData attr)
    {
        foreach (var namedArg in attr.NamedArguments)
            if (namedArg.Key == "IncludeInherited" && namedArg.Value.Value is bool val)
                return val;
        return false;
    }

    private static HashSet<string> GetFlattenProperties(AttributeData attr)
    {
        var result = new HashSet<string>();
        foreach (var namedArg in attr.NamedArguments)
        {
            if (namedArg.Key != "Flatten") continue;
            foreach (var item in namedArg.Value.Values)
                if (item.Value is string name)
                    result.Add(name);
        }
        return result;
    }

    private static Dictionary<string, string> GetRenameMap(INamedTypeSymbol classSymbol)
    {
        var map = new Dictionary<string, string>();
        foreach (var a in classSymbol.GetAttributes())
        {
            if (a.AttributeClass?.ToDisplayString() != RenamePropertyAttributeFullName) continue;
            if (a.ConstructorArguments.Length < 2) continue;
            if (a.ConstructorArguments[0].Value is not string sourceName) continue;
            if (a.ConstructorArguments[1].Value is not string targetName) continue;
            map[sourceName] = targetName;
        }
        return map;
    }

    private static bool TryGetFromModelAttributeData(INamedTypeSymbol classSymbol, out AttributeData? attr)
    {
        attr = null;
        foreach (var a in classSymbol.GetAttributes())
        {
            if (a.AttributeClass?.ToDisplayString() == FromModelAttributeFullName)
            {
                attr = a;
                break;
            }
        }

        return attr is not null && attr.ConstructorArguments.Length > 0;
    }

    private static bool TryGetModelSymbol(AttributeData attr, out INamedTypeSymbol? modelSymbol)
    {
        var arg = attr.ConstructorArguments[0];
        modelSymbol = null;

        if (arg.Kind != TypedConstantKind.Type) return false;
        if (arg.Value is not INamedTypeSymbol ms) return false;

        modelSymbol = ms;
        return true;
    }

    private static void Emit(SourceProductionContext context, ClassTarget target)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        var indent = "";
        if (target.Namespace is not null)
        {
            sb.AppendLine($"namespace {target.Namespace}");
            sb.AppendLine("{");
            indent = "    ";
        }

        sb.AppendLine($"{indent}{target.Accessibility} partial class {target.ClassName}");
        sb.AppendLine($"{indent}{{");

        foreach (var prop in target.Properties)
        {
            var accessors = new StringBuilder(" {");
            if (prop.HasGetter) accessors.Append(" get;");
            if (prop.IsInitOnly) accessors.Append(" init;");
            else if (prop.HasSetter) accessors.Append(" set;");
            accessors.Append(" }");

            var modifier = prop.IsRequired ? "required " : "";
            var line = $"{indent}    public {modifier}{prop.Type} {prop.Name}{accessors}";
            if (prop.Initializer is not null)
                line += $" = {prop.Initializer};";
            sb.AppendLine(line);
        }

        sb.AppendLine($"{indent}}}");

        if (target.Namespace is not null)
            sb.AppendLine("}");

        var hintName = target.Namespace is not null
            ? $"{target.Namespace}.{target.ClassName}.g.cs"
            : $"{target.ClassName}.g.cs";

        context.AddSource(hintName, SourceText.From(sb.ToString(), Encoding.UTF8));
    }
}
