using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace FromModel;

[Generator]
public sealed partial class FromModelGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx =>
        {
            foreach (var source in DefaultSource.All)
                ctx.AddSource(source.Filename, SourceText.From(source.Code, Encoding.UTF8));
        });

        var pipeline = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => SyntaxTransformer.IsPartialClassWithAttributes(node),
                transform: static (ctx, _) => SyntaxTransformer.ExtractClassTarget(ctx))
            .Where(static target => target is not null);

        context.RegisterSourceOutput(pipeline, static (ctx, target) => Emit(ctx, target!));
    }

    private static void Emit(SourceProductionContext context, ClassTarget target)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        var indent = "";
        if (target.Namespace is not null)
        {
            sb.AppendLine($"namespace {target.Namespace}");
            sb.AppendLine("{");
            indent = "    ";
        }

        sb.AppendLine($"{indent}{target.Accessibility} partial class {target.ClassName}");
        sb.AppendLine($"{indent}{{");

        foreach (var prop in target.Properties)
        {
            var accessors = new StringBuilder(" {");
            if (prop.HasGetter) accessors.Append(" get;");
            if (prop.IsInitOnly) accessors.Append(" init;");
            else if (prop.HasSetter) accessors.Append(" set;");
            accessors.Append(" }");

            var modifier = prop.IsRequired ? "required " : "";
            var line = $"{indent}    public {modifier}{prop.Type} {prop.Name}{accessors}";
            if (prop.Initializer is not null)
                line += $" = {prop.Initializer};";
            sb.AppendLine(line);
        }

        sb.AppendLine($"{indent}}}");

        if (target.Namespace is not null)
            sb.AppendLine("}");

        var hintName = target.Namespace is not null
            ? $"{target.Namespace}.{target.ClassName}.g.cs"
            : $"{target.ClassName}.g.cs";

        context.AddSource(hintName, SourceText.From(sb.ToString(), Encoding.UTF8));
    }
}
