namespace Gener8;

internal record DefaultSource(string Name, string Code, string Filename)
{
    
    public static readonly DefaultSource RepositoryTypeEnum = new(
        Name: "Gener8.RepositoryType",
        Code: """
            // <auto-generated/>
            namespace Gener8
            {
                public enum RepositoryType
                {
                    None = 0,
                    DynamoDb = 1,
                    MongoDb = 2
                }
            }
        """,
        Filename: "RepositoryType.g.cs"
    );

    public static readonly DefaultSource FromModelAttribute = new(
        Name: "Gener8.FromModelAttribute",
        Code: """
            // <auto-generated/>
            #nullable enable
            namespace Gener8
            {
                [System.AttributeUsage(System.AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
                public sealed class FromModelAttribute : System.Attribute
                {
                    public System.Type ModelType { get; }
                    public string[] Ignore { get; set; } = System.Array.Empty<string>();
                    public bool IncludeInherited { get; set; }
                    public string[] Flatten { get; set; } = System.Array.Empty<string>();
                    public FlattenPrefix FlattenPrefix { get; set; }
                    public RepositoryType Repository { get; set; }

                    public FromModelAttribute(System.Type modelType)
                    {
                        ModelType = modelType;
                    }
                }
            }
        """,
        Filename: "FromModelAttribute.g.cs"
    );

    public static readonly DefaultSource RepositoryAbstractClass = new(
        Name: "Gener8.Repository",
        Code: """
            // <auto-generated/>
            #nullable enable
            namespace Gener8
            {
                public abstract class Repository<T> where T : class
                {
                    public abstract global::System.Threading.Tasks.Task<T?> GetByIdAsync(string id, global::System.Threading.CancellationToken cancellationToken = default);
                    public abstract global::System.Threading.Tasks.Task<global::System.Collections.Generic.IEnumerable<T>> GetAllAsync(global::System.Threading.CancellationToken cancellationToken = default);
                    public abstract global::System.Threading.Tasks.Task SaveAsync(T entity, global::System.Threading.CancellationToken cancellationToken = default);
                    public abstract global::System.Threading.Tasks.Task DeleteAsync(string id, global::System.Threading.CancellationToken cancellationToken = default);
                }
            }
        """,
        Filename: "Repository.g.cs"
    );

    public static readonly DefaultSource DynamoDbRepositorySettingsClass = new(
        Name: "Gener8.DynamoDbRepositorySettings",
        Code: """
            // <auto-generated/>
            #nullable enable
            namespace Gener8
            {
                public sealed class DynamoDbRepositorySettings
                {
                    public string TableName { get; set; } = string.Empty;
                }
            }
        """,
        Filename: "DynamoDbRepositorySettings.g.cs"
    );

    public static readonly DefaultSource MongoDbRepositorySettingsClass = new(
        Name: "Gener8.MongoDbRepositorySettings",
        Code: """
            // <auto-generated/>
            #nullable enable
            namespace Gener8
            {
                public sealed class MongoDbRepositorySettings
                {
                    public string DatabaseName { get; set; } = string.Empty;
                    public string CollectionName { get; set; } = string.Empty;
                }
            }
        """,
        Filename: "MongoDbRepositorySettings.g.cs"
    );

    public static readonly DefaultSource TypeMappingAttribute = new(
        Name: "Gener8.TypeMappingAttribute",
        Code: """
            // <auto-generated/>
            namespace Gener8
            {
                [System.AttributeUsage(System.AttributeTargets.Class, Inherited = false, AllowMultiple = true)]
                public sealed class TypeMappingAttribute : System.Attribute
                {
                    public System.Type SourceType { get; }
                    public System.Type TargetType { get; }

                    public TypeMappingAttribute(System.Type sourceType, System.Type targetType)
                    {
                        SourceType = sourceType;
                        TargetType = targetType;
                    }
                }
            }
        """,
        Filename: "TypeMappingAttribute.g.cs"
    );

    public static readonly DefaultSource RenamePropertyAttribute = new(
        Name: "Gener8.RenamePropertyAttribute",
        Code: """
            // <auto-generated/>
            namespace Gener8
            {
                [System.AttributeUsage(System.AttributeTargets.Class, Inherited = false, AllowMultiple = true)]
                public sealed class RenamePropertyAttribute : System.Attribute
                {
                    public string SourceName { get; }
                    public string TargetName { get; }

                    public RenamePropertyAttribute(string sourceName, string targetName)
                    {
                        SourceName = sourceName;
                        TargetName = targetName;
                    }
                }
            }
        """,
        Filename: "RenamePropertyAttribute.g.cs"
    );

    public static readonly DefaultSource FlattenPrefixEnum = new(
        Name: "Gener8.FlattenPrefix",
        Code: """
            // <auto-generated/>
            namespace Gener8
            {
                public enum FlattenPrefix
                {
                    Parent = 0,
                    None = 1,
                    Gaped = 2
                }
            }
        """,
        Filename: "FlattenPrefix.g.cs"
    );

    public static DefaultSource[] All { get; } =
    [
        RepositoryTypeEnum,
        FlattenPrefixEnum,
        FromModelAttribute,
        TypeMappingAttribute,
        RenamePropertyAttribute,
        RepositoryAbstractClass,
        DynamoDbRepositorySettingsClass,
        MongoDbRepositorySettingsClass,
    ];
}
