using System.Collections.Generic;

namespace Gener8;

internal partial record DefaultSource(string Name, string Code, string Filename)
{
    public static readonly DefaultSource RepositoryTypeEnum = new(
        Name: "Gener8.RepositoryType",
        Code: """
        // <auto-generated/>
        namespace Gener8;

        public enum RepositoryType
        {
            None = 0,
            DynamoDb = 1,
            MongoDb = 2,
            Custom = 3
        }
        """,
        Filename: "RepositoryType.g.cs"
    );

    public static readonly DefaultSource FromModelAttribute = new(
        Name: "Gener8.FromModelAttribute",
        Code: """
        // <auto-generated/>
        #nullable enable
        namespace Gener8;

        [System.AttributeUsage(System.AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
        public sealed class FromModelAttribute(System.Type modelType) : System.Attribute
        {
            public System.Type ModelType { get; } = modelType;
            public string[] Ignore { get; set; } = [];
            public bool IncludeInherited { get; set; }
            public string[] Flatten { get; set; } = [];
            public FlattenPrefix FlattenPrefix { get; set; }
            public RepositoryType Repository { get; set; }
            public string[] DtoNamespaces { get; set; } = [];
        }
        """,
        Filename: "FromModelAttribute.g.cs"
    );

    public static readonly DefaultSource IRepositoryInterface = new(
        Name: "Gener8.IRepository",
        Code: """
        // <auto-generated/>
        #nullable enable
        namespace Gener8;

        public interface IRepository<TModel> where TModel : class
        {
            global::System.Threading.Tasks.Task<TModel?> GetByIdAsync(object id, global::System.Threading.CancellationToken cancellationToken = default);
            global::System.Threading.Tasks.Task SaveAsync(TModel entity, global::System.Threading.CancellationToken cancellationToken = default);
            global::System.Threading.Tasks.Task DeleteAsync(TModel entity, global::System.Threading.CancellationToken cancellationToken = default);
            global::System.Threading.Tasks.Task DeleteByIdAsync(object id, global::System.Threading.CancellationToken cancellationToken = default);
            global::System.Threading.Tasks.Task<global::System.Collections.Generic.IEnumerable<TModel>> GetAllAsync(global::System.Threading.CancellationToken cancellationToken = default);
        }
        """,
        Filename: "IRepository.g.cs"
    );

    public static readonly DefaultSource MongoDbRepositoryBaseClass = new(
        Name: "Gener8.MongoDbRepository",
        Code: """
        // <auto-generated/>
        using System;
        using System.Collections.Generic;
        using System.Threading;
        using System.Threading.Tasks;
        using MongoDB.Bson.Serialization;
        using MongoDB.Driver;
        
        #nullable enable
        namespace Gener8;

        public interface IMongoDbRepositoryContext
        {
            IMongoDatabase Context { get; }
        }

        public abstract partial class MongoDbRepository<TModel, TDto> : IRepository<TModel> where TModel : class where TDto : class
        {
            protected readonly IMongoCollection<TDto> Collection;
            protected readonly IMongoDbRepositoryContext Context;

            protected MongoDbRepository(IMongoDbRepositoryContext context, string collectionName)
            {
                Context = context;
                Collection = context.Context.GetCollection<TDto>(collectionName);
            }
        
            abstract protected TModel ToModel(TDto dto);
        
            abstract protected TDto ToDto(TModel model);

            public virtual async Task<TModel?> GetByIdAsync(object id, CancellationToken cancellationToken = default)
            {
                var filter = Builders<TDto>.Filter.Eq("_id", id);
                var dto = await Collection.Find(filter).FirstOrDefaultAsync(cancellationToken);
                return ToModel(dto);
            }

            public virtual async Task SaveAsync(TModel entity, CancellationToken cancellationToken = default)
            {
                var id = GetIdFromEntity(entity);
                var filter = Builders<TDto>.Filter.Eq("_id", id);
                var options = new ReplaceOptions { IsUpsert = true };

                await Collection.ReplaceOneAsync(filter, ToDto(entity), options, cancellationToken);
            }

            public virtual async Task DeleteAsync(TModel entity, CancellationToken cancellationToken = default)
            {
                var id = GetIdFromEntity(entity);
                var filter = Builders<TDto>.Filter.Eq("_id", id);

                await Collection.DeleteOneAsync(filter, cancellationToken);
            }

            public virtual async Task DeleteByIdAsync(object id, CancellationToken cancellationToken = default)
            {
                var filter = Builders<TDto>.Filter.Eq("_id", id);
                await Collection.DeleteOneAsync(filter, cancellationToken);
            }

            public virtual async Task<IEnumerable<TModel>> GetAllAsync(CancellationToken cancellationToken = default)
            {
                var dtos = await Collection.Find(Builders<TDto>.Filter.Empty).ToListAsync(cancellationToken);
                return dtos.Select(dto => ToModel(dto));
            }

            protected virtual object GetIdFromEntity(TModel entity)
            {
                var classMap = BsonClassMap.LookupClassMap(typeof(TModel));
                if (classMap.IdMemberMap == null)
                {
                    throw new InvalidOperationException($"No Id member found for type {typeof(TModel).Name}.");
                }

                return classMap.IdMemberMap.Getter(entity);
            }
        }
        """,
        Filename: "MongoDbRepository.g.cs"
    );

    public static readonly DefaultSource CustomRepositoryBaseClass = new(
        Name: "Gener8.CustomRepository",
        Code: """
        // <auto-generated/>
        #nullable enable
        namespace Gener8;

        public interface IRepositoryContext
        {
        }
            
        public abstract partial class RepositoryBase<TModel, TDto> : IRepository<TModel>
            where TModel : class
            where TDto : class
        {
            protected readonly IRepositoryContext Context;

            protected RepositoryBase(IRepositoryContext context) => Context = context;
        
            abstract protected TModel ToModel(TDto dto);
        
            abstract protected TDto ToDto(TModel model);
        }
        """,
        Filename: "CustomRepository.g.cs"
    );

    public static readonly DefaultSource TypeMappingAttribute = new(
        Name: "Gener8.TypeMappingAttribute",
        Code: """
        // <auto-generated/>
        namespace Gener8;

        [System.AttributeUsage(System.AttributeTargets.Class, Inherited = false, AllowMultiple = true)]
        public sealed class TypeMappingAttribute(System.Type sourceType, System.Type targetType) : System.Attribute
        {
            public System.Type SourceType { get; } = sourceType;
            public System.Type TargetType { get; } = targetType;
        }
        """,
        Filename: "TypeMappingAttribute.g.cs"
    );

    public static readonly DefaultSource RenamePropertyAttribute = new(
        Name: "Gener8.RenamePropertyAttribute",
        Code: """
        // <auto-generated/>
        namespace Gener8;

        [System.AttributeUsage(System.AttributeTargets.Class, Inherited = false, AllowMultiple = true)]
        public sealed class RenamePropertyAttribute(string sourceName, string targetName) : System.Attribute
        {
            public string SourceName { get; } = sourceName;
            public string TargetName { get; } = targetName;
        }
        """,
        Filename: "RenamePropertyAttribute.g.cs"
    );

    public static readonly DefaultSource FlattenPrefixEnum = new(
        Name: "Gener8.FlattenPrefix",
        Code: """
        // <auto-generated/>
        namespace Gener8;

        public enum FlattenPrefix
        {
            Parent = 0,
            None = 1,
            Gaped = 2
        }
        """,
        Filename: "FlattenPrefix.g.cs"
    );

    public static IEnumerable<DefaultSource> Essentials =>
    [
        RepositoryTypeEnum,
        FlattenPrefixEnum,
        FromModelAttribute,
        TypeMappingAttribute,
        RenamePropertyAttribute,
        IRepositoryInterface,
    ];
}
