namespace Gener8;

partial record DefaultSource
{
    public static readonly DefaultSource EnumToStringConverter = new(
        Name: "Gener8.Converters.EnumToStringConverter",
        Code: """
        // <auto-generated/>
        #nullable enable
        using Amazon.DynamoDBv2.DataModel;
        using Amazon.DynamoDBv2.DocumentModel;
        using System;

        namespace Gener8.Converters;

        public class EnumToStringConverter<TEnum> : IPropertyConverter where TEnum : struct, Enum
        {
            public object FromEntry(DynamoDBEntry entry) => Enum.Parse<TEnum>(entry.AsString());

            public DynamoDBEntry ToEntry(object value) => new Primitive(value.ToString());
        }
        """,
        Filename: "EnumToStringConverter.g.cs"
    );

    public static readonly DefaultSource NullableEnumToStringConverter = new(
        Name: "Gener8.Converters.NullableEnumToStringConverter",
        Code: """
        // <auto-generated/>
        #nullable enable
        using Amazon.DynamoDBv2.DataModel;
        using Amazon.DynamoDBv2.DocumentModel;
        using System;

        namespace Gener8.Converters;

        public class NullableEnumToStringConverter<TEnum> : IPropertyConverter where TEnum : struct, Enum
        {
            public object? FromEntry(DynamoDBEntry? entry)
            {
                var s = entry?.AsString();
                if (string.IsNullOrEmpty(s))
                {
                    return null;
                }

                return Enum.Parse<TEnum>(s);
            }

            public DynamoDBEntry ToEntry(object? value)
            {
                if (value is TEnum e)
                {
                    return new Primitive(e.ToString());
                }
                return new DynamoDBNull();
            }
        }
        """,
        Filename: "NullableEnumToStringConverter.g.cs"
    );

    public static readonly DefaultSource EnumListToStringListConverter = new(
        Name: "Gener8.Converters.EnumListToStringListConverter",
        Code: """
        // <auto-generated/>
        #nullable enable
        using Amazon.DynamoDBv2.DataModel;
        using Amazon.DynamoDBv2.DocumentModel;
        using System;
        using System.Collections.Generic;
        using System.Linq;

        namespace Gener8.Converters;

        public class EnumListToStringListConverter<TEnum> : IPropertyConverter where TEnum : struct, Enum
        {
            public object? FromEntry(DynamoDBEntry? entry)
            {
                var stringList = entry?.AsListOfString();
                if (stringList == null) return null;
                return stringList.Select(s => Enum.Parse<TEnum>(s)).ToList();
            }

            public DynamoDBEntry ToEntry(object? value)
            {
                if (value is IEnumerable<TEnum> list)
                    return new DynamoDBList(list.Select(e => (DynamoDBEntry)new Primitive(e.ToString())));
                return new DynamoDBNull();
            }
        }
        """,
        Filename: "EnumListToStringListConverter.g.cs"
        );

    public static readonly DefaultSource NullableEnumListToStringListConverter = new(
        Name: "Gener8.Converters.NullableEnumListToStringListConverter",
        Code: """
        // <auto-generated/>
        #nullable enable
        using Amazon.DynamoDBv2.DataModel;
        using Amazon.DynamoDBv2.DocumentModel;
        using System;
        using System.Collections.Generic;
        using System.Linq;

        namespace Gener8.Converters;

        public class NullableEnumListToStringListConverter<TEnum> : IPropertyConverter where TEnum : struct, Enum
        {
            public object? FromEntry(DynamoDBEntry? entry)
            {
                var dynamoList = entry as DynamoDBList;
                if (dynamoList == null) return null;
                return dynamoList.Entries
                    .Select(e =>
                    {
                        var s = e.AsString();
                        return string.IsNullOrEmpty(s) ? (TEnum?)null : Enum.Parse<TEnum>(s);
                    })
                    .ToList();
            }

            public DynamoDBEntry ToEntry(object? value)
            {
                if (value is IEnumerable<TEnum?> list)
                    return new DynamoDBList(list.Select<TEnum?, DynamoDBEntry>(e =>
                        e.HasValue ? new Primitive(e.Value.ToString()) : new DynamoDBNull()));
                return new DynamoDBNull();
            }
        }
        """,
        Filename: "NullableEnumListToStringListConverter.g.cs"
        );

    public static readonly DefaultSource DynamoDbRepositoryBaseClass = new(
        Name: "Gener8.DynamoDbRepository",
        Code: """
        // <auto-generated/>
        using System.Collections.Generic;
        using System.Threading;
        using System.Threading.Tasks;
        using Amazon.DynamoDBv2.DataModel;
        using System.Linq;

        #nullable enable
        namespace Gener8;

        public interface ICompositeKeyRepository<TModel> : IRepository<TModel> where TModel : class
        {
            Task<TModel?> GetByIdAsync(object hashKey, object rangeKey, CancellationToken cancellationToken = default);
            Task DeleteByIdAsync(object hashKey, object rangeKey, CancellationToken cancellationToken = default);
        }

        public interface IDynamoDbRepositoryContext
        {
            IDynamoDBContext Context { get; }
        }

        public abstract partial class DynamoDbRepository<TModel, TDto>(IDynamoDbRepositoryContext context) : ICompositeKeyRepository<TModel>
            where TModel : class
            where TDto : class
        {
            protected readonly IDynamoDbRepositoryContext Context = context;
            protected IDynamoDBContext DynamoDbContext => Context.Context;

            abstract protected TModel ToModel(TDto dto);

            abstract protected TDto ToDto(TModel model);

            // --- IRepository<T> Implementation (Single Key) ---

            public virtual async Task<TModel?> GetByIdAsync(object id, CancellationToken cancellationToken = default)
            {
                var dto = await DynamoDbContext.LoadAsync<TDto>(id, cancellationToken);
                return ToModel(dto);
            }

            public virtual async Task SaveAsync(TModel entity, CancellationToken cancellationToken = default)
            {
                await DynamoDbContext.SaveAsync(ToDto(entity), cancellationToken);
            }

            public virtual async Task DeleteAsync(TModel entity, CancellationToken cancellationToken = default)
            {
                await DynamoDbContext.DeleteAsync(ToDto(entity), cancellationToken);
            }

            public virtual async Task DeleteByIdAsync(object id, CancellationToken cancellationToken = default)
            {
                await DynamoDbContext.DeleteAsync<TDto>(id, cancellationToken);
            }

            public virtual async Task<IEnumerable<TModel>> GetAllAsync(CancellationToken cancellationToken = default)
            {
                var search = DynamoDbContext.ScanAsync<TDto>(new List<ScanCondition>());
                return (await search.GetRemainingAsync(cancellationToken)).Select(dto => ToModel(dto));
            }

            // --- ICompositeKeyRepository<T> Implementation (Two Keys) ---

            public virtual async Task<TModel?> GetByIdAsync(object hashKey, object rangeKey, CancellationToken cancellationToken = default)
            {
                var dto = await DynamoDbContext.LoadAsync<TDto>(hashKey, rangeKey, cancellationToken);
                return ToModel(dto);
            }

            public virtual async Task DeleteByIdAsync(object hashKey, object rangeKey, CancellationToken cancellationToken = default)
            {
                await DynamoDbContext.DeleteAsync<TDto>(hashKey, rangeKey, cancellationToken);
            }
        }
        """,
        Filename: "DynamoDbRepository.g.cs"
    );
}
