using Gener8.Contexts;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Text;

namespace Gener8;

internal static class SourceProducer
{
    public static void Emit(SourceProductionContext context, TargetClass target)
    {
        EmitModel(context, target);
        EmitExtensions(context, target);
        if (target.Repository != RepositoryKind.None)
            EmitRepository(context, target);
    }

    private static void EmitModel(SourceProductionContext context, TargetClass target)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");

        if(target.Repository == RepositoryKind.DynamoDb)
        {
            sb.AppendLine("using Amazon.DynamoDBv2.DataModel;");
            sb.AppendLine("using Gener8.Converters;");
        }

        if (target.Repository == RepositoryKind.MongoDb)
        {
            sb.AppendLine("using MongoDB.Bson;");
            sb.AppendLine("using MongoDB.Bson.Serialization.Attributes;");
        }

        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        if (target.Namespace is not null)
            sb.AppendLine($"namespace {target.Namespace};");

        sb.AppendLine($"{target.Accessibility} partial class {target.ClassName}");
        sb.AppendLine($"{{");

        foreach (var prop in target.Properties)
        {
            if (prop.IsUserDeclared) continue;

            if (prop.TypeData.IsEnum || prop.TypeData.EnumCollectionElementType is not null)
            {
                if(target.Repository == RepositoryKind.DynamoDb)
                {
                    string converterType;
                    if (prop.TypeData.EnumCollectionElementType is { } elemType)
                    {
                        var bare = elemType.EndsWith("?")
                            ? elemType.Substring(0, elemType.Length - 1)
                            : elemType;
                        converterType = elemType.EndsWith("?")
                            ? $"NullableEnumListToStringListConverter<{bare}>"
                            : $"EnumListToStringListConverter<{elemType}>";
                    }
                    else
                    {
                        converterType = prop.TypeData.IsNullable
                            ? $"NullableEnumToStringConverter<{prop.TypeData.Type.Substring(0, prop.TypeData.Type.Length - 1)}>"
                            : $"EnumToStringConverter<{prop.TypeData.Type}>";
                    }

                    sb.AppendLine($"    [DynamoDBProperty(typeof({converterType}))]");
                }

                if(target.Repository == RepositoryKind.MongoDb)
                {
                    sb.AppendLine("    [BsonRepresentation(BsonType.String)]");
                }
            }

            var accessors = new StringBuilder(" {");
            if (prop.HasGetter) accessors.Append(" get;");
            if (prop.IsInitOnly) accessors.Append(" init;");
            else if (prop.HasSetter) accessors.Append(" set;");
            accessors.Append(" }");

            var modifier = prop.IsRequired ? "required " : "";
            var line = $"    public {modifier}{prop.TypeData.Type} {prop.Name}{accessors}";
            if (prop.Initializer is not null)
                line += $" = {prop.Initializer};";
            sb.AppendLine(line);
        }

        sb.AppendLine($"}}");

        var hintName = target.Namespace is not null
            ? $"{target.Namespace}.{target.ClassName}.g.cs"
            : $"{target.ClassName}.g.cs";

        context.AddSource(hintName, SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static void EmitExtensions(SourceProductionContext context, TargetClass target)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine();

        if (target.Namespace is not null)
            sb.AppendLine($"namespace {target.Namespace};");

        var extAccessibility = target.Accessibility == "public" ? "public" : "internal";
        sb.AppendLine($"{extAccessibility} static class {target.ClassName}Extensions");
        sb.AppendLine($"{{");

        // Pre-pass: group non-type-mapped flattened properties by parent for ToModel reconstruction.
        var flattenedByParent = new Dictionary<string, List<PropertyData>>();
        foreach (var prop in target.Properties)
        {
            if (prop.Flattened is null || prop.TypeData.HasTypeMapping) continue;

            if (!flattenedByParent.TryGetValue(prop.Flattened.ParentName, out var list))
                flattenedByParent[prop.Flattened.ParentName] = list = [];

            list.Add(prop);
        }

        // ToModel: dto -> model
        sb.AppendLine($"    public static {target.Model.FullName} ToModel(this {target.ClassName} dto)");
        sb.AppendLine($"    {{");
        sb.AppendLine($"        return new {target.Model.FullName}");
        sb.AppendLine($"        {{");
        foreach (var prop in target.Properties)
        {
            if (prop.Flattened is not null) continue;
            if (!prop.HasGetter) continue;
            if (!prop.HasSetter && !prop.IsInitOnly) continue;

            var modelPropName = prop.ModelPropertyName ?? prop.Name;
            var nc = prop.TypeData.IsNullable ? "?" : "";
            var dtoRead = prop.TypeData.HasTypeMapping
                ? prop.TypeData.HasGenericTypeMapping
                    ? BuildProjectedCollectionMapping($"dto.{prop.Name}", "ToModel", prop.TypeData.IsNullable)
                    : $"dto.{prop.Name}{nc}.ToModel()"
                : $"dto.{prop.Name}";

            sb.AppendLine($"            {modelPropName} = {dtoRead},");
        }
        // Reconstruct flattened parent objects from their spread DTO properties.
        foreach (var kvp in flattenedByParent)
        {
            var parentName = kvp.Key;
            var flatProps = kvp.Value;
            var firstProp = flatProps[0];
            var parentTypeFullName = firstProp.Flattened!.ParentTypeFullName;
            var parentIsNullable = firstProp.Flattened!.ReadPath.Contains("?.");

            if (parentIsNullable)
            {
                // Use the first property as the null indicator. C# flow analysis narrows it
                // to non-null inside the false branch of the ternary.
                sb.AppendLine($"            {parentName} = dto.{firstProp.Name} is null ? null : new {parentTypeFullName}");
                sb.AppendLine($"            {{");
                for (var i = 0; i < flatProps.Count; i++)
                {
                    var p = flatProps[i];
                    // The first property is flow-narrowed after the null check above.
                    // Subsequent properties whose type was made nullable solely by the parent
                    // (not originally nullable) need '!' to satisfy the non-nullable target slot.
                    var bang = (i > 0 && !p.Flattened!.OriginallyNullable) ? "!" : "";
                    sb.AppendLine($"                {p.Flattened!.NestedPropertyName} = dto.{p.Name}{bang},");
                }
                sb.AppendLine($"            }},");
            }
            else
            {
                sb.AppendLine($"            {parentName} = new {parentTypeFullName}");
                sb.AppendLine($"            {{");
                foreach (var p in flatProps)
                    sb.AppendLine($"                {p.Flattened!.NestedPropertyName} = dto.{p.Name},");
                sb.AppendLine($"            }},");
            }
        }
        sb.AppendLine($"        }};");
        sb.AppendLine($"    }}");
        sb.AppendLine();

        // ToDto: model -> dto
        sb.AppendLine($"    public static {target.ClassName} ToDto(this {target.Model.FullName} model)");
        sb.AppendLine($"    {{");
        sb.AppendLine($"        return new {target.ClassName}");
        sb.AppendLine($"        {{");
        foreach (var prop in target.Properties)
        {
            if (!prop.HasSetter && !prop.IsInitOnly) continue;
            string rhs;
            if (prop.Flattened is not null)
            {
                if (prop.TypeData.HasTypeMapping) continue;  // flattened + type-mapped: skip, cannot chain

                if (prop.TypeData.NeedsSpreadAssignment)
                    rhs = BuildFlattenedSpreadRhs(prop.Flattened.ReadPath);
                else
                    rhs = $"model.{prop.Flattened.ReadPath}";
            }
            else
            {
                var modelPropName = prop.ModelPropertyName ?? prop.Name;
                var nc = prop.TypeData.Type.EndsWith("?") ? "?" : "";
                if (prop.TypeData.NeedsSpreadAssignment)
                {
                    // Abstract collection (IReadOnlyCollection<T> etc.) remapped to List<T>.
                    // Use collection expression spread; handle nullable model property with null guard.
                    var collectionSource = $"model.{modelPropName}";
                    var projectedCollection = prop.TypeData.HasGenericTypeMapping
                        ? $"{collectionSource}.Select(m => m.ToDto())"
                        : collectionSource;

                    rhs = prop.TypeData.Type.EndsWith("?")
                        ? $"{collectionSource} is null ? null : [.. {projectedCollection}]"
                        : $"[.. {projectedCollection}]";
                }
                else
                {
                    rhs = prop.TypeData.HasTypeMapping
                        ? prop.TypeData.HasGenericTypeMapping
                            ? BuildProjectedCollectionMapping($"model.{modelPropName}", "ToDto", prop.TypeData.IsNullable)
                            : $"model.{modelPropName}{nc}.ToDto()"
                        : $"model.{modelPropName}";
                }
            }
            sb.AppendLine($"            {prop.Name} = {rhs},");
        }
        sb.AppendLine($"        }};");
        sb.AppendLine($"    }}");

        sb.AppendLine($"}}");

        var hintName = target.Namespace is not null
            ? $"{target.Namespace}.{target.ClassName}Extensions.g.cs"
            : $"{target.ClassName}Extensions.g.cs";

        context.AddSource(hintName, SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    // Builds the right-hand-side expression for a flattened property that also needs a spread
    // (e.g. the nested property type was IReadOnlyCollection<T> remapped to List<T>).
    // FlattenedReadPath is "Parent.Child" (non-nullable parent) or "Parent?.Child" (nullable).
    private static string BuildFlattenedSpreadRhs(string flattenedReadPath)
    {
        var nullIdx = flattenedReadPath.IndexOf("?.", System.StringComparison.Ordinal);
        if (nullIdx >= 0)
        {
            var parent = flattenedReadPath.Substring(0, nullIdx);
            var child = flattenedReadPath.Substring(nullIdx + 2);
            // model.Parent?.Child is null → either parent or child is null; use parent!.Child in the spread.
            return $"model.{parent}?.{child} is null ? null : [.. model.{parent}!.{child}]";
        }
        return $"[.. model.{flattenedReadPath}]";
    }

    private static string BuildProjectedCollectionMapping(string source, string mappingMethod, bool isNullable)
    {
        var projectedCollection = $"{source}.Select(m => m.{mappingMethod}())";
        return isNullable
            ? $"{source} is null ? null : [.. {projectedCollection}]"
            : $"[.. {projectedCollection}]";
    }

    // Emits all auto-generated DTOs, skipping any whose model is already covered by a
    // manually-annotated DTO (userAnnotatedModelNames) and de-duplicating by hint name.
    public static void EmitAutoDtos(
        SourceProductionContext context,
        ImmutableArray<TargetClass> targets,
        ImmutableArray<string> userAnnotatedModelNames)
    {
        var skipModels = new HashSet<string>(userAnnotatedModelNames);
        var emitted = new HashSet<string>();

        foreach (var target in targets)
        {
            if (skipModels.Contains(target.Model.FullName)) continue;

            var key = target.Namespace is not null
                ? $"{target.Namespace}.{target.ClassName}"
                : target.ClassName;

            if (!emitted.Add(key)) continue;

            EmitModel(context, target);
            EmitExtensions(context, target);
        }
    }

    public static void EmitRepositoryBaseClasses(SourceProductionContext context, ImmutableArray<RepositoryKind> kinds)
    {
        var emittedDynamo = false;
        var emittedMongo = false;
        var emittedCustom = false;

        foreach (var kind in kinds)
        {
            if (kind == RepositoryKind.DynamoDb && !emittedDynamo)
            {
                emittedDynamo = true;

                context.AddSource(DefaultSource.EnumToStringConverter.Filename,
                    SourceText.From(DefaultSource.EnumToStringConverter.Code, Encoding.UTF8));

                context.AddSource(DefaultSource.NullableEnumToStringConverter.Filename,
                    SourceText.From(DefaultSource.NullableEnumToStringConverter.Code, Encoding.UTF8));

                context.AddSource(DefaultSource.EnumListToStringListConverter.Filename,
                    SourceText.From(DefaultSource.EnumListToStringListConverter.Code, Encoding.UTF8));

                context.AddSource(DefaultSource.NullableEnumListToStringListConverter.Filename,
                    SourceText.From(DefaultSource.NullableEnumListToStringListConverter.Code, Encoding.UTF8));

                context.AddSource(DefaultSource.DynamoDbRepositoryBaseClass.Filename,
                    SourceText.From(DefaultSource.DynamoDbRepositoryBaseClass.Code, Encoding.UTF8));
            }
            else if (kind == RepositoryKind.MongoDb && !emittedMongo)
            {
                emittedMongo = true;
                context.AddSource(DefaultSource.MongoDbRepositoryBaseClass.Filename,
                    SourceText.From(DefaultSource.MongoDbRepositoryBaseClass.Code, Encoding.UTF8));
            }
            else if (kind == RepositoryKind.Custom && !emittedCustom)
            {
                emittedCustom = true;
                context.AddSource(DefaultSource.CustomRepositoryBaseClass.Filename,
                    SourceText.From(DefaultSource.CustomRepositoryBaseClass.Code, Encoding.UTF8));
            }
        }
    }

    private static void EmitRepository(SourceProductionContext context, TargetClass target)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using Gener8;");
        sb.AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        if (target.Namespace is not null)
            sb.AppendLine($"namespace {target.Namespace};");

        var className = target.ClassName;
        var repoClassName = $"{target.Model.Name}Repository";

        if (target.Repository == RepositoryKind.DynamoDb)
        {
            sb.AppendLine($"{target.Accessibility} partial class {repoClassName} : Gener8.DynamoDbRepository<{target.Model.FullName}, {className}>");
            sb.AppendLine($"{{");
            sb.AppendLine($"    public {repoClassName}(IDynamoDbRepositoryContext context) : base(context) {{}}");
        }

        if (target.Repository == RepositoryKind.MongoDb)
        {
            sb.AppendLine($"{target.Accessibility} partial class {repoClassName} : Gener8.MongoDbRepository<{target.Model.FullName}, {className}>");
            sb.AppendLine($"{{");
            sb.AppendLine($"    public {repoClassName}(IMongoDbRepositoryContext context) : base(context, \"{className}\") {{}}");
        }

        if (target.Repository == RepositoryKind.Custom)
        {
            sb.AppendLine($"{target.Accessibility} partial class {repoClassName} : Gener8.RepositoryBase<{target.Model.FullName}, {className}>");
            sb.AppendLine($"{{");
            sb.AppendLine($"    public {repoClassName}(IRepositoryContext context) : base(context) {{}}");
        }

        sb.AppendLine($"    protected override {target.Model.FullName} ToModel({className} dto) => dto.ToModel();");
        sb.AppendLine($"    protected override {className} ToDto({target.Model.FullName} model) => model.ToDto();");
        sb.AppendLine($"}}");

        var hintName = target.Namespace is not null
            ? $"{target.Namespace}.{repoClassName}.g.cs"
            : $"{repoClassName}.g.cs";

        context.AddSource(hintName, SourceText.From(sb.ToString(), Encoding.UTF8));
    }
}
