using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Text;

namespace Gener8;

internal static class SourceProducer
{
    public static void Emit(SourceProductionContext context, ClassTarget target)
    {
        EmitModel(context, target);
        EmitExtensions(context, target);
        if (target.Repository != RepositoryKind.None)
            EmitRepository(context, target);
    }

    private static void EmitModel(SourceProductionContext context, ClassTarget target)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        var indent = "";
        if (target.Namespace is not null)
        {
            sb.AppendLine($"namespace {target.Namespace}");
            sb.AppendLine("{");
            indent = "    ";
        }

        sb.AppendLine($"{indent}{target.Accessibility} partial class {target.ClassName}");
        sb.AppendLine($"{indent}{{");

        foreach (var prop in target.Properties)
        {
            if (prop.IsUserDeclared) continue;

            var accessors = new StringBuilder(" {");
            if (prop.HasGetter) accessors.Append(" get;");
            if (prop.IsInitOnly) accessors.Append(" init;");
            else if (prop.HasSetter) accessors.Append(" set;");
            accessors.Append(" }");

            var modifier = prop.IsRequired ? "required " : "";
            var line = $"{indent}    public {modifier}{prop.Type} {prop.Name}{accessors}";
            if (prop.Initializer is not null)
                line += $" = {prop.Initializer};";
            sb.AppendLine(line);
        }

        sb.AppendLine($"{indent}}}");

        if (target.Namespace is not null)
            sb.AppendLine("}");

        var hintName = target.Namespace is not null
            ? $"{target.Namespace}.{target.ClassName}.g.cs"
            : $"{target.ClassName}.g.cs";

        context.AddSource(hintName, SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static void EmitExtensions(SourceProductionContext context, ClassTarget target)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        var indent = "";
        if (target.Namespace is not null)
        {
            sb.AppendLine($"namespace {target.Namespace}");
            sb.AppendLine("{");
            indent = "    ";
        }

        var extAccessibility = target.Accessibility == "public" ? "public" : "internal";
        sb.AppendLine($"{indent}{extAccessibility} static class {target.ClassName}Extensions");
        sb.AppendLine($"{indent}{{");

        // Pre-pass: group non-type-mapped flattened properties by parent for ToModel reconstruction.
        var flattenedByParent = new Dictionary<string, List<PropertyData>>();
        foreach (var prop in target.Properties)
        {
            if (prop.FlattenedParentName is null || prop.HasTypeMapping) continue;
            if (!flattenedByParent.TryGetValue(prop.FlattenedParentName, out var list))
                flattenedByParent[prop.FlattenedParentName] = list = [];
            list.Add(prop);
        }

        // ToModel: dto -> model
        sb.AppendLine($"{indent}    public static {target.ModelFullName} ToModel(this {target.ClassName} dto)");
        sb.AppendLine($"{indent}    {{");
        sb.AppendLine($"{indent}        return new {target.ModelFullName}");
        sb.AppendLine($"{indent}        {{");
        foreach (var prop in target.Properties)
        {
            if (prop.FlattenedReadPath is not null) continue;
            if (!prop.HasGetter) continue;
            if (!prop.HasSetter && !prop.IsInitOnly) continue;
            var modelPropName = prop.ModelPropertyName ?? prop.Name;
            var nc = prop.Type.EndsWith("?") ? "?" : "";
            var dtoRead = prop.HasTypeMapping
                ? $"dto.{prop.Name}{nc}.ToModel()"
                : $"dto.{prop.Name}";
            sb.AppendLine($"{indent}            {modelPropName} = {dtoRead},");
        }
        // Reconstruct flattened parent objects from their spread DTO properties.
        foreach (var kvp in flattenedByParent)
        {
            var parentName = kvp.Key;
            var flatProps = kvp.Value;
            var firstProp = flatProps[0];
            var parentTypeFullName = firstProp.FlattenedParentTypeFullName!;
            var parentIsNullable = firstProp.FlattenedReadPath!.Contains("?.");

            if (parentIsNullable)
            {
                // Use the first property as the null indicator. C# flow analysis narrows it
                // to non-null inside the false branch of the ternary.
                sb.AppendLine($"{indent}            {parentName} = dto.{firstProp.Name} is null ? null : new {parentTypeFullName}");
                sb.AppendLine($"{indent}            {{");
                for (var i = 0; i < flatProps.Count; i++)
                {
                    var p = flatProps[i];
                    // The first property is flow-narrowed after the null check above.
                    // Subsequent properties whose type was made nullable solely by the parent
                    // (not originally nullable) need '!' to satisfy the non-nullable target slot.
                    var bang = (i > 0 && !p.FlattenedOriginallyNullable) ? "!" : "";
                    sb.AppendLine($"{indent}                {p.FlattenedNestedPropertyName} = dto.{p.Name}{bang},");
                }
                sb.AppendLine($"{indent}            }},");
            }
            else
            {
                sb.AppendLine($"{indent}            {parentName} = new {parentTypeFullName}");
                sb.AppendLine($"{indent}            {{");
                foreach (var p in flatProps)
                    sb.AppendLine($"{indent}                {p.FlattenedNestedPropertyName} = dto.{p.Name},");
                sb.AppendLine($"{indent}            }},");
            }
        }
        sb.AppendLine($"{indent}        }};");
        sb.AppendLine($"{indent}    }}");
        sb.AppendLine();

        // ToDto: model -> dto
        sb.AppendLine($"{indent}    public static {target.ClassName} ToDto(this {target.ModelFullName} model)");
        sb.AppendLine($"{indent}    {{");
        sb.AppendLine($"{indent}        return new {target.ClassName}");
        sb.AppendLine($"{indent}        {{");
        foreach (var prop in target.Properties)
        {
            if (!prop.HasSetter && !prop.IsInitOnly) continue;
            string rhs;
            if (prop.FlattenedReadPath is not null)
            {
                if (prop.HasTypeMapping) continue;  // flattened + type-mapped: skip, cannot chain
                if (prop.NeedsSpreadAssignment)
                    rhs = BuildFlattenedSpreadRhs(prop.FlattenedReadPath);
                else
                    rhs = $"model.{prop.FlattenedReadPath}";
            }
            else
            {
                var modelPropName = prop.ModelPropertyName ?? prop.Name;
                var nc = prop.Type.EndsWith("?") ? "?" : "";
                if (prop.NeedsSpreadAssignment)
                {
                    // Abstract collection (IReadOnlyCollection<T> etc.) remapped to List<T>.
                    // Use collection expression spread; handle nullable model property with null guard.
                    rhs = prop.Type.EndsWith("?")
                        ? $"model.{modelPropName} is null ? null : [.. model.{modelPropName}]"
                        : $"[.. model.{modelPropName}]";
                }
                else
                {
                    rhs = prop.HasTypeMapping
                        ? $"model.{modelPropName}{nc}.ToDto()"
                        : $"model.{modelPropName}";
                }
            }
            sb.AppendLine($"{indent}            {prop.Name} = {rhs},");
        }
        sb.AppendLine($"{indent}        }};");
        sb.AppendLine($"{indent}    }}");

        sb.AppendLine($"{indent}}}");

        if (target.Namespace is not null)
            sb.AppendLine("}");

        var hintName = target.Namespace is not null
            ? $"{target.Namespace}.{target.ClassName}Extensions.g.cs"
            : $"{target.ClassName}Extensions.g.cs";

        context.AddSource(hintName, SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    // Builds the right-hand-side expression for a flattened property that also needs a spread
    // (e.g. the nested property type was IReadOnlyCollection<T> remapped to List<T>).
    // FlattenedReadPath is "Parent.Child" (non-nullable parent) or "Parent?.Child" (nullable).
    private static string BuildFlattenedSpreadRhs(string flattenedReadPath)
    {
        var nullIdx = flattenedReadPath.IndexOf("?.", System.StringComparison.Ordinal);
        if (nullIdx >= 0)
        {
            var parent = flattenedReadPath.Substring(0, nullIdx);
            var child = flattenedReadPath.Substring(nullIdx + 2);
            // model.Parent?.Child is null → either parent or child is null; use parent!.Child in the spread.
            return $"model.{parent}?.{child} is null ? null : [.. model.{parent}!.{child}]";
        }
        return $"[.. model.{flattenedReadPath}]";
    }

    public static void EmitRepositoryBaseClasses(SourceProductionContext context, ImmutableArray<RepositoryKind> kinds)
    {
        var emittedDynamo = false;
        var emittedMongo = false;
        var emittedCustom = false;

        foreach (var kind in kinds)
        {
            if (kind == RepositoryKind.DynamoDb && !emittedDynamo)
            {
                emittedDynamo = true;
                context.AddSource(DefaultSource.DynamoDbRepositoryBaseClass.Filename,
                    SourceText.From(DefaultSource.DynamoDbRepositoryBaseClass.Code, Encoding.UTF8));
            }
            else if (kind == RepositoryKind.MongoDb && !emittedMongo)
            {
                emittedMongo = true;
                context.AddSource(DefaultSource.MongoDbRepositoryBaseClass.Filename,
                    SourceText.From(DefaultSource.MongoDbRepositoryBaseClass.Code, Encoding.UTF8));
            }
            else if (kind == RepositoryKind.Custom && !emittedCustom)
            {
                emittedCustom = true;
                context.AddSource(DefaultSource.CustomRepositoryBaseClass.Filename,
                    SourceText.From(DefaultSource.CustomRepositoryBaseClass.Code, Encoding.UTF8));
            }
        }
    }

    private static void EmitRepository(SourceProductionContext context, ClassTarget target)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using Gener8;");
        sb.AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        var indent = "";
        if (target.Namespace is not null)
        {
            sb.AppendLine($"namespace {target.Namespace}");
            sb.AppendLine("{");
            indent = "    ";
        }

        var className = target.ClassName;
        var repoClassName = $"{target.ModelName}Repository";

        if (target.Repository == RepositoryKind.DynamoDb)
        {
            sb.AppendLine($"{indent}{target.Accessibility} partial class {repoClassName} : Gener8.DynamoDbRepository<{target.ModelFullName}, {className}>");
            sb.AppendLine($"{indent}{{");
            sb.AppendLine($"{indent}    public {repoClassName}(IDynamoDbRepositoryContext context) : base(context) {{}}");
        }

        if (target.Repository == RepositoryKind.MongoDb)
        {
            sb.AppendLine($"{indent}{target.Accessibility} partial class {repoClassName} : Gener8.MongoDbRepository<{target.ModelFullName}, {className}>");
            sb.AppendLine($"{indent}{{");
            sb.AppendLine($"{indent}    public {repoClassName}(IMongoDbRepositoryContext context) : base(context, \"{className}\") {{}}");
        }

        if (target.Repository == RepositoryKind.Custom)
        {
            sb.AppendLine($"{indent}{target.Accessibility} partial class {repoClassName} : Gener8.RepositoryBase<{target.ModelFullName}, {className}>");
            sb.AppendLine($"{indent}{{");
            sb.AppendLine($"{indent}    public {repoClassName}(IRepositoryContext context) : base(context) {{}}");
        }

        sb.AppendLine($"{indent}    protected override {target.ModelFullName} ToModel({className} dto) => dto.ToModel();");
        sb.AppendLine($"{indent}    protected override {className} ToDto({target.ModelFullName} model) => model.ToDto();");
        sb.AppendLine($"{indent}}}");

        if (target.Namespace is not null)
            sb.AppendLine("}");

        var hintName = target.Namespace is not null
            ? $"{target.Namespace}.{repoClassName}.g.cs"
            : $"{repoClassName}.g.cs";

        context.AddSource(hintName, SourceText.From(sb.ToString(), Encoding.UTF8));
    }
}
