using System.Collections.Immutable;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.Text;

namespace Gener8;

internal static class SourceProducer
{
    public static void Emit(SourceProductionContext context, ClassTarget target)
    {
        EmitModel(context, target);
        EmitExtensions(context, target);
        if (target.Repository != RepositoryKind.None)
            EmitRepository(context, target);
    }

    private static void EmitModel(SourceProductionContext context, ClassTarget target)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        var indent = "";
        if (target.Namespace is not null)
        {
            sb.AppendLine($"namespace {target.Namespace}");
            sb.AppendLine("{");
            indent = "    ";
        }

        sb.AppendLine($"{indent}{target.Accessibility} partial class {target.ClassName}");
        sb.AppendLine($"{indent}{{");

        foreach (var prop in target.Properties)
        {
            var accessors = new StringBuilder(" {");
            if (prop.HasGetter) accessors.Append(" get;");
            if (prop.IsInitOnly) accessors.Append(" init;");
            else if (prop.HasSetter) accessors.Append(" set;");
            accessors.Append(" }");

            var modifier = prop.IsRequired ? "required " : "";
            var line = $"{indent}    public {modifier}{prop.Type} {prop.Name}{accessors}";
            if (prop.Initializer is not null)
                line += $" = {prop.Initializer};";
            sb.AppendLine(line);
        }

        sb.AppendLine($"{indent}}}");

        if (target.Namespace is not null)
            sb.AppendLine("}");

        var hintName = target.Namespace is not null
            ? $"{target.Namespace}.{target.ClassName}.g.cs"
            : $"{target.ClassName}.g.cs";

        context.AddSource(hintName, SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static void EmitExtensions(SourceProductionContext context, ClassTarget target)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        var indent = "";
        if (target.Namespace is not null)
        {
            sb.AppendLine($"namespace {target.Namespace}");
            sb.AppendLine("{");
            indent = "    ";
        }

        var extAccessibility = target.Accessibility == "public" ? "public" : "internal";
        sb.AppendLine($"{indent}{extAccessibility} static class {target.ClassName}Extensions");
        sb.AppendLine($"{indent}{{");

        // ToModel: dto → model
        sb.AppendLine($"{indent}    public static {target.ModelFullName} ToModel(this {target.ClassName} dto)");
        sb.AppendLine($"{indent}    {{");
        sb.AppendLine($"{indent}        return new {target.ModelFullName}");
        sb.AppendLine($"{indent}        {{");
        foreach (var prop in target.Properties)
        {
            if (prop.FlattenedReadPath is not null) continue;
            if (!prop.HasGetter) continue;
            if (!prop.HasSetter && !prop.IsInitOnly) continue;
            var modelPropName = prop.ModelPropertyName ?? prop.Name;
            var nc = prop.Type.EndsWith("?") ? "?" : "";
            var dtoRead = prop.HasTypeMapping
                ? $"dto.{prop.Name}{nc}.ToModel()"
                : $"dto.{prop.Name}";
            sb.AppendLine($"{indent}            {modelPropName} = {dtoRead},");
        }
        sb.AppendLine($"{indent}        }};");
        sb.AppendLine($"{indent}    }}");
        sb.AppendLine();

        // ToDto: model → dto
        sb.AppendLine($"{indent}    public static {target.ClassName} ToDto(this {target.ModelFullName} model)");
        sb.AppendLine($"{indent}    {{");
        sb.AppendLine($"{indent}        return new {target.ClassName}");
        sb.AppendLine($"{indent}        {{");
        foreach (var prop in target.Properties)
        {
            if (!prop.HasSetter && !prop.IsInitOnly) continue;
            string rhs;
            if (prop.FlattenedReadPath is not null)
            {
                if (prop.HasTypeMapping) continue;  // flattened + type-mapped: skip, cannot chain
                rhs = $"model.{prop.FlattenedReadPath}";
            }
            else
            {
                var modelPropName = prop.ModelPropertyName ?? prop.Name;
                var nc = prop.Type.EndsWith("?") ? "?" : "";
                rhs = prop.HasTypeMapping
                    ? $"model.{modelPropName}{nc}.ToDto()"
                    : $"model.{modelPropName}";
            }
            sb.AppendLine($"{indent}            {prop.Name} = {rhs},");
        }
        sb.AppendLine($"{indent}        }};");
        sb.AppendLine($"{indent}    }}");

        sb.AppendLine($"{indent}}}");

        if (target.Namespace is not null)
            sb.AppendLine("}");

        var hintName = target.Namespace is not null
            ? $"{target.Namespace}.{target.ClassName}Extensions.g.cs"
            : $"{target.ClassName}Extensions.g.cs";

        context.AddSource(hintName, SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    public static void EmitRepositoryBaseClasses(SourceProductionContext context, ImmutableArray<RepositoryKind> kinds)
    {
        var emittedDynamo = false;
        var emittedMongo = false;
        foreach (var kind in kinds)
        {
            if (kind == RepositoryKind.DynamoDb && !emittedDynamo)
            {
                emittedDynamo = true;
                context.AddSource(DefaultSource.DynamoDbRepositoryBaseClass.Filename,
                    SourceText.From(DefaultSource.DynamoDbRepositoryBaseClass.Code, Encoding.UTF8));
            }
            else if (kind == RepositoryKind.MongoDb && !emittedMongo)
            {
                emittedMongo = true;
                context.AddSource(DefaultSource.MongoDbRepositoryBaseClass.Filename,
                    SourceText.From(DefaultSource.MongoDbRepositoryBaseClass.Code, Encoding.UTF8));
            }
        }
    }

    private static void EmitRepository(SourceProductionContext context, ClassTarget target)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        var indent = "";
        if (target.Namespace is not null)
        {
            sb.AppendLine($"namespace {target.Namespace}");
            sb.AppendLine("{");
            indent = "    ";
        }

        var className = target.ClassName;

        if (target.Repository == RepositoryKind.DynamoDb)
        {
            var repoClassName = $"{className}Repository";
            sb.AppendLine($"{indent}{target.Accessibility} partial class {repoClassName} : Gener8.DynamoDbRepository<{target.ModelFullName}, {className}>");
            sb.AppendLine($"{indent}{{");
            sb.AppendLine($"{indent}    public {repoClassName}(Amazon.DynamoDBv2.DataModel.IDynamoDBContext context) : base(context) {{}}");
        }
        
        if (target.Repository == RepositoryKind.MongoDb)
        {
            var repoClassName = $"{className}Repository";
            sb.AppendLine($"{indent}{target.Accessibility} partial class {repoClassName} : Gener8.MongoDbRepository<{target.ModelFullName}, {className}>");
            sb.AppendLine($"{indent}{{");
            sb.AppendLine($"{indent}    public {repoClassName}(MongoDB.Driver.IMongoDatabase database) : base(database, \"{className}\") {{}}");
        }

        sb.AppendLine($"{indent}    protected override {target.ModelFullName} ToModel({className} dto) => dto.ToModel();");
        sb.AppendLine($"{indent}    protected override {className} ToDto({target.ModelFullName} model) => model.ToDto();");
        sb.AppendLine($"{indent}}}");

        if (target.Namespace is not null)
            sb.AppendLine("}");

        var hintName = target.Namespace is not null
            ? $"{target.Namespace}.{className}Repository.g.cs"
            : $"{className}Repository.g.cs";

        context.AddSource(hintName, SourceText.From(sb.ToString(), Encoding.UTF8));
    }
}
